apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagrameks
  region: us-west-2


  eksctl create cluster --name udagrameks --region=us-west-2 --nodes-min=2 --nodes-max=3


docker build . -t gammer4live/udagram-reverseproxy:v7
docker push [Dockerhub-username]/udagram-reverseproxy:v7
